name: Seek in the void

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Seek the void
        run: |
          current_year=$(date "+%Y")
          current_month=$(date "+%m")
          current_datetime=$(date "+%Y%m%d")
          curl -o 0.nodes https://www.freeclashnode.com/uploads/${current_year}/${current_month}/0-${current_datetime}.txt
          curl -o 1.nodes https://www.freeclashnode.com/uploads/${current_year}/${current_month}/1-${current_datetime}.txt
          curl -o 2.nodes https://www.freeclashnode.com/uploads/${current_year}/${current_month}/2-${current_datetime}.txt
          curl -o 3.nodes https://www.freeclashnode.com/uploads/${current_year}/${current_month}/3-${current_datetime}.txt
          curl -o 4.nodes https://www.freeclashnode.com/uploads/${current_year}/${current_month}/4-${current_datetime}.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update at $(date)" || echo "No changes to commit"
      - name : xxx
        run: |
          echo ${{ secrets.VOID_SEEKER }}
      - name: Push changes
        run: |
          echo git push https://x-access-token:${{ secrets.VOID_SEEKER }}@github.com/${{ github.repository }}.git main